import typer
import subprocess
import yaml
import os
from pathlib import Path

app = typer.Typer(help="OpenClaw SECURE Management CLI (BYOC MITM Proxy Edition)")

@app.command()
def start(
    workspace: str = typer.Option(..., help="Path to host workspace to mount"),
    sandbox_name: str = typer.Option("openclaw-sandbox", help="Name of the sandbox"),
    agent: str = typer.Option("openclaw", help="Base agent to run (default: openclaw)"),
):
    typer.echo(f"Starting {agent} securely attached to {workspace}...")
    workspace_path = Path(workspace).absolute()
    
    mitm_ca_dir = Path.home() / ".mitmproxy"
    mitm_ca_cert = mitm_ca_dir / "mitmproxy-ca-cert.pem"
    mitm_ca_dir.mkdir(parents=True, exist_ok=True)
    
    subprocess.run(["openshell", "gateway", "start"], check=False)
    
    policy_dir = Path("policies").absolute()
    policy_dir.mkdir(exist_ok=True)
    policy_path = policy_dir / f"{sandbox_name}_policy.yaml"
    
    policy_doc = {
        "version": 1,
        "filesystem_policy": {
            "include_workdir": True,
            "read_only": [str(mitm_ca_dir)]
        },
        "network_policies": {
            "mitm_proxy_access": {
                "name": "Local MitM Proxy",
                "endpoints": [{"host": "host.docker.internal", "port": 8080}]
            },
            "openai_api": {
                "name": "OpenAI API",
                "endpoints": [{"host": "api.openai.com", "port": 443}]
            },
            "anthropic_api": {
                "name": "Anthropic API",
                "endpoints": [{"host": "api.anthropic.com", "port": 443}]
            },
            "github_access": {
                "name": "GitHub API",
                "endpoints": [{"host": "api.github.com", "port": 443}]
            }
        }
    }
    
    with open(policy_path, "w") as f:
        yaml.dump(policy_doc, f)
        
    # Generate BYOC Context
    byoc_dir = workspace_path / ".openshell_byoc"
    byoc_dir.mkdir(parents=True, exist_ok=True)
    dockerfile_path = byoc_dir / "Dockerfile"
    
    with open(dockerfile_path, "w") as f:
        f.write(f"FROM ghcr.io/nvidia/openshell-community/sandboxes/{agent}:latest\n")
        f.write("ENV HTTPS_PROXY=\"http://host.docker.internal:8080\"\n")
        f.write("ENV HTTP_PROXY=\"http://host.docker.internal:8080\"\n")
        f.write(f"ENV NODE_EXTRA_CA_CERTS=\"{mitm_ca_cert}\"\n")
        
    typer.echo(f"Generated BYOC Context at {byoc_dir}")
        
    cmd = [
        "openshell", "sandbox", "create",
        "--name", sandbox_name,
        "--policy", str(policy_path),
        "--from", str(byoc_dir)
    ]
    
    try:
        subprocess.run(cmd, check=True, cwd=str(workspace_path))
        typer.secho("Sandbox built and created successfully using BYOC orchestration!", fg=typer.colors.GREEN)
    except subprocess.CalledProcessError:
        typer.secho("Failed to create Sandbox using BYOC.", fg=typer.colors.RED)
        raise typer.Exit(1)

@app.command()
def set_policy(sandbox_name: str = typer.Argument(...), domain: str = typer.Option(...)):
    subprocess.run(["openshell", "policy", "set", sandbox_name, "--allow-domain", domain], check=False)

@app.command()
def stop(sandbox_name: str = typer.Argument("openclaw-sandbox")):
    subprocess.run(["openshell", "sandbox", "delete", sandbox_name], check=False)

if __name__ == "__main__":
    app()
